### ISSUE TITLE
feature request: decoding an OscMessage from a byte[]

### ISSUE THREAD

**Issue by orgicus** [sojamo/oscp5#11]
Hi,

First off, thank you for sharing this awesome library!

I was wondering if it's possible to construct an `OscMessage` from a `byte[]` (essentially decode a `byte[]` of valid OSC bytes for a message). I haven't found anything in the library yet.
Would it be possible to have an extra constructor or a static method that takes in a `byte[]` and returns the decoded `OscMessage` ?

At the moment my workaround is to create an `OscP5` instance and a `NetAddress` instance using the same port to `flush` the `byte[]` to the same sketch so it gets decoded into an OscMessage. It works, but I'm hoping there's a simpler/more elegant way ?

Thank you very much,
George

**Comment by sojamo** [comment]
Hi George,
there is another osc library that I have been working on which contains a function [bytesToMessage](https://github.com/sojamo/osc/blob/4d3a12e16ba85c559a226cd1d5c782009e8f2533/java/src/main/java/sojamo/osc/OscParser.java#L109) that does what you are looking for ([a working gist](https://gist.github.com/sojamo/d141d8593265a90c2f2ee2aa514a7ff3) example) it takes a byte array and returns an OscMessage. I can carry it over to oscP5 in a future release, but as you can tell from my last commit I haven't made updates to oscP5 for a while.

**Comment by orgicus** [comment]
Hi Andreas,

The resources you've shared are extremely useful.
Initially I tried to hack my way through it, but realised there is a conflict between sojamo.osc's `OscMessage` and oscP5's `OscMessage`. I'll switch the whole osc part to sojamo.osc to keep it consistent.

Thank you very much for the support,
George
