### ISSUE TITLE
OSC stops when application not focused in background

### ISSUE THREAD

**Issue by Lyptik** [sojamo/oscp5#3]
Hello there,

On OSX, when using oscP5 in Processing, OSC stops after a while when the application is in the background (i.e. not focused). It does sucessfully resume when you click on the window.

Is it a normal behaviour and is there anyway to prevent this behaviour ?
It seems to happen only on OSX.

If you want to give a try with our app : https://github.com/Theoriz/Augmenta-Simulator

Best,

David C.

**Comment by sojamo** [comment]
Hi, I could not reproduce the behavior you are encountering. I can't find any oscP5 code used in the  link you mention. Do you have a simple example (preferably with no dependencies to other libraries) that produces and highlights this issue? When you say OSC stops what does that mean? It stops receiving, sending, both? When you say after a while, is that after a couple of seconds or minutes?

**Comment by Lyptik** [comment]
Hey, 

Thanks for the answer !

It did stop sending (it did not seem to be appnapp doing this on OSX). and resuming later when focusing again on the window.

Actually we cannot repoduce it anymore either, seems like it's been fixed with Processing3 and or/our current config. Thanks a lot for the support anyway.

Best,

David C.
