### ISSUE TITLE
osc.send parameters

### ISSUE THREAD

**Issue by gr91** [sojamo/oscp5#5]
Hello,
I'm trying to work with Processing and Pure Data using OSC Protocol . Looking for some examples in "basic" folder I found the _osc.send_ parameters are wrong `osc.send( receiver , "/test" , random( 255 ) , random( 255 ) , random( 255 ) );` and the sketch does not run.
In the example sketches on OscP5 website the object _osc.send_ present different parameters `oscP5.send(myMessage, myRemoteLocation)`.
Am I doing something wrong?
Thanks!

**Comment by sojamo** [comment]
you might be using an older version of oscP5 (0.9.9 ?), the current version is 2.0.4 and is available under [releases](https://github.com/sojamo/oscp5/releases). 
`osc.send( receiver , "/test" , random( 255 ) , random( 255 ) , random( 255 ) );` works under 2.0.4 but not with 0.9.9, here use `oscP5.send(myMessage, myRemoteLocation);` instead.

**Comment by gr91** [comment]
Hi,
It's true. I found an old version using Processing tool for libraries management.
Thanks for your answer.
